---
title: "Day 7a"
author: "Carmen"
date: "2024-08-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages.

```{r}
library(tidyverse)
library(palmerpenguins)
library(lubridate)
```

### Refresher 1:

```{r}
new_penguins <- penguins %>%
  select(-c(year, sex)) %>%
  mutate(body_mass_kg = body_mass_g / 1000) %>%
  rename(location = island) %>%
  filter(location == c("Biscoe", "Dream"))
```

### Refresher 2:

```{r}
new_penguins_2 <- penguins %>%
  filter(species == "Adelie" & !is.na(flipper_length_mm)) %>%
  group_by(sex) %>%
  summarize(mean_flipper_mm = mean(flipper_length_mm),
            sd_flipper = sd(flipper_length_mm), 
            sample_size = n())
```

## Task 3. Practice with joins.

```{r}
install.packages("datapasta")
animals <- tibble::tribble(
  ~location,   ~species,  ~maturity,
   "lagoon",   "bobcat",    "adult",
    "bluff",   "coyote", "juvenile",
    "creek",      "fox",    "adult",
     "oaks", "squirrel", "juvenile",
    "bluff",   "bobcat",    "adult"
  )
sites <- tibble::tribble(
           ~location,      ~full_site_name, ~jurisdiction,
             "beach",       "Goleta Beach",     "SB City",
            "lagoon",        "UCSB Lagoon",        "UCSB",
             "bluff",       "Ellwood Mesa",     "SB City",
              "oaks", "Fremont Campground",        "USFS"
           )
full_join_example <- full_join(animals, sites)
left_join_example <- left_join(animals, sites)
right_join_example <- right_join(animals, sites)
inner_join_example <- inner_join(animals, sites)

semi_join_example <- semi_join(animals, sites)
#is the same as:
semi_join_test <- animals %>%
  filter(location %in% sites$location)

anti_join_example <- anti_join(animals, sites)
#is the same as:
anti_join_test <- animals %>%
  filter(!location %in% sites$location)
  
  
#---- for loop?----  
joins <- c("full", "left", "right", "inner")
#examples <- vector("character", length = length(joins))

for (i in seq_along(joins)) {
  name <- paste0(joins[i], "_join_example_loop")
  fun <- paste0(joins[i], "_join")
  examples[i] <- print(get(fun)(animals, sites))
}
```

## Practice with '{lubridate}'

```{r}
library(tidyverse)
```

## Examples with dates.

```{r}
my_date <- "03-15-1988"
mdy(my_date) #tell lubridate what order the date is in

my_date <- "11/7/2003"
mdy(my_date)

my_date <- "08-Jun-1974"
dmy(my_date)

my_date <- "19610518"
ymd(my_date)
```

## Examples with time. 

```{r}
time <- "2020-08-12 11:18"
time <- ymd_hm(time)
class(time)
with_tz(time, "America/Los_Angeles")
with_tz(time, "Australia/Sydney")
my_time <- ymd_hms(time)
week(my_time)
day(my_time)
hour(my_time)
minute(my_time)
second(my_time)

#---- more examples ----

comp_time <- Sys.time()
with_tz(comp_time, "Europe/Belgrade")

teddy_bday <- ymd("20170615")
teddy_bday
wday(teddy_bday, label = TRUE)
week(teddy_bday)
year(teddy_bday)
month(teddy_bday)
```

## Examples.

```{r}
urchin_counts <- tribble(
  ~date, ~species, ~size_mm,
  "10/3/2020", "purple", 55,
  "10/4/2020", "red", 48,
  "11/17/2020", "red", 67
)

urchin_counts_ymd <- urchin_counts %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  mutate(year = year(date),
         month = month(date),
         day = day(date))

urchin_counts_ymd %>%
  group_by(year) %>%
  summarize(total = n())
```

## Practice with time intervals. 

```{r}
day_1 <- ymd("2020-01-06")
day_2 <- ymd("2020-05-18")
day_3 <- ymd("2020-05-19")

time_interval <- interval(day_1, day_2)
time_length(time_interval, "week")
time_length(time_interval, "year")
```

## Wrangling with {stringr}

```{r}
my_string <- "Teddy loves eating salmon and socks."
my_string %>% str_detect("love")
my_string %>% str_detect("pup")

my_string <- c("burritos", "fish taco", "Taco salad")
my_string %>% str_detect("fish")

skywalkers <- starwars %>%
  filter(str_detect(name, "Skywalker"))

skywalkers

firewalkers <- skywalkers %>%
  mutate(name = str_replace(name, pattern = "Sky", replacement = "Fire"))

head(firewalkers)
```



```{r}
feedback <- c(" I ate    some nachos", "Wednesday morning   ")
str_squish(feedback)
str_trim(feedback) #removes leading and trailing white spaces

str_to_lower(feedback)
str_to_upper(feedback)
str_to_title(feedback)

str_count(feedback, patter = "nachos")
```

